image: rustlang/rust:nightly

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules
  - .yarn

before_script:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

wave:
  services:
    - yarn:1
  script:
    - yarn install
    - yarn build

