
stages:
- build

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules

before_script:
  - yarn install
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

wave:
  stage: build
  image: rustlang/rust:nightly
  script:
    - yarn build
  artifacts:
    paths:
    - public
  only: 
  - master

