image: node:latest

include:
    - template: SAST.gitlab-ci.yml
    - template: Dependency-Scanning.gitlab-ci.yml

stages:
    - test
    - deploy

variables:
    PUBLIC_URL: /wave

test:
    stage: test
    script:
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
        - source $HOME/.cargo/env
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - yarn install --frozen-lockfile
        - yarn test
    cache:
        key: ${CI_PROJECT_ID}
        paths:
            - node_modules
    except:
        changes:
            - "*.md"

pages:
    stage: deploy
    script:
        ##
        ## Install ssh-agent if not already installed, it is required by Docker.
        ##
        - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"

        ##
        ## Install rsync if not already installed
        ##
        - "which rsync || ( apt-get update -y && apt-get install rsync -y )"

        ##
        ## Run ssh-agent (inside the build environment)
        ##
        - eval $(ssh-agent -s)

        ##
        ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
        ## We're using tr to fix line endings which makes ed25519 keys work
        ## without extra base64 encoding.
        ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
        ##
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

        ##
        ## Create the SSH directory and give it the right permissions
        ##
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh

        ##
        ## Scan the keys of the server.
        ##
        - ssh-keyscan pyxxilated.studio >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts

        ##
        ## Deploy to gitlab and to the server
        ##
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
        - source $HOME/.cargo/env
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - yarn install --frozen-lockfile
        - yarn build
        - mv public _public
        - mv build public
        - rsync -hrvz --delete -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" public gitlab@pyxxilated.studio:/var/www/wave/
        - cp public/index.html public/404.html
    artifacts:
        paths:
            - public # mandatory, other folder won't work
    cache:
        key: ${CI_PROJECT_ID}
        paths:
            - node_modules
    environment:
        name: staging
        url: https://www.pyxxilated.studio/wave
    only:
        - master
    except:
        changes:
            - "*.md"
