include:
    - template: SAST.gitlab-ci.yml
    - template: Dependency-Scanning.gitlab-ci.yml

variables:
    PUBLIC_URL: /wave

pages:
    image: node:latest
    stage: deploy
    script:
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
        - source $HOME/.cargo/env
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - yarn install
        - yarn build
        - cp public/index.html public/404.html
        - mv public _public
        - mv build public
    artifacts:
        paths:
            - public # mandatory, other folder won't work
    only:
        - master
    cache:
        key: ${CI_PROJECT_ID}
        paths:
            - node_modules
    except:
        changes:
            - "*.md"
